GET http://localhost:3000




###

GET http://localhost:3000/details







###

POST  http://localhost:3000/searchbycategory
content-type: application/json

{"jobCategory":"IT"}

###
GET http://localhost:4040/